# application.properties
spring.application.name=officelend
spring.datasource.url=jdbc:mysql://localhost:3306/proyectoWebLenguajes
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Configuración de Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
# JWT
jwt.secret=claveSuperSecretaDeMasDe32CaracteresFTWLinuxx
jwt.expiration=3600000
# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
# Configuración de carga de imágenes
equipment.upload.dir=uploads/equipment/
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
